name: Example/Test
on: push

jobs:
  test:
    name: Example/Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Upload FAB to Linc
        uses: gregbrimble/linc-fab-action@main
        with:
          api_key: ${{ secrets.LINC_API_KEY }}
          site_name: linc-fab-action-example
          working_directory: "/github/workspace/example"
